package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/markbates/pop"
	"github.com/pkg/errors"
	"github.com/postcert/entitlements/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (IdentityEntitlement)
// DB Table: Plural (identity_entitlements)
// Resource: Plural (IdentityEntitlements)
// Path: Plural (/identity_entitlements)
// View Template Folder: Plural (/templates/identity_entitlements/)

// IdentityEntitlementsResource is the resource for the IdentityEntitlement model
type IdentityEntitlementsResource struct {
	buffalo.Resource
}

// List gets all IdentityEntitlements. This function is mapped to the path
// GET /identity_entitlements
func (v IdentityEntitlementsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)

	identityEntitlements := &models.IdentityEntitlements{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all IdentityEntitlements from the DB
	if err := q.All(identityEntitlements); err != nil {
		return errors.WithStack(err)
	}

	// Make IdentityEntitlements available inside the html template
	c.Set("identityEntitlements", identityEntitlements)

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.HTML("identity_entitlements/index.html"))
}

// Show gets the data for one IdentityEntitlement. This function is mapped to
// the path GET /identity_entitlements/{identity_entitlement_id}
func (v IdentityEntitlementsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)

	// Allocate an empty IdentityEntitlement
	identityEntitlement := &models.IdentityEntitlement{}

	// To find the IdentityEntitlement the parameter identity_entitlement_id is used.
	if err := tx.Find(identityEntitlement, c.Param("identity_entitlement_id")); err != nil {
		return c.Error(404, err)
	}

	// Make identityEntitlement available inside the html template
	c.Set("identityEntitlement", identityEntitlement)

	return c.Render(200, r.HTML("identity_entitlements/show.html"))
}

// New renders the form for creating a new IdentityEntitlement.
// This function is mapped to the path GET /identity_entitlements/new
func (v IdentityEntitlementsResource) New(c buffalo.Context) error {
	// Make identityEntitlement available inside the html template
	c.Set("identityEntitlement", &models.IdentityEntitlement{})

	return c.Render(200, r.HTML("identity_entitlements/new.html"))
}

// Create adds a IdentityEntitlement to the DB. This function is mapped to the
// path POST /identity_entitlements
func (v IdentityEntitlementsResource) Create(c buffalo.Context) error {
	// Allocate an empty IdentityEntitlement
	identityEntitlement := &models.IdentityEntitlement{}

	// Bind identityEntitlement to the html form elements
	if err := c.Bind(identityEntitlement); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(identityEntitlement)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make identityEntitlement available inside the html template
		c.Set("identity_entitlement", identityEntitlement)

		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("identity_entitlements/new.html"))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "IdentityEntitlement was created successfully")

	// and redirect to the identity_entitlements index page
	return c.Redirect(302, "/identity_entitlements/%s", identityEntitlement.ID)
}

// Edit renders a edit form for a IdentityEntitlement. This function is
// mapped to the path GET /identity_entitlements/{identity_entitlement_id}/edit
func (v IdentityEntitlementsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)

	// Allocate an empty IdentityEntitlement
	identityEntitlement := &models.IdentityEntitlement{}

	if err := tx.Find(identityEntitlement, c.Param("identity_entitlement_id")); err != nil {
		return c.Error(404, err)
	}

	// Make identityEntitlement available inside the html template
	c.Set("identityEntitlement", identityEntitlement)
	return c.Render(200, r.HTML("identity_entitlements/edit.html"))
}

// Update changes a IdentityEntitlement in the DB. This function is mapped to
// the path PUT /identity_entitlements/{identity_entitlement_id}
func (v IdentityEntitlementsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)

	// Allocate an empty IdentityEntitlement
	identityEntitlement := &models.IdentityEntitlement{}

	if err := tx.Find(identityEntitlement, c.Param("identity_entitlement_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind IdentityEntitlement to the html form elements
	if err := c.Bind(identityEntitlement); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(identityEntitlement)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make identityEntitlement available inside the html template
		c.Set("identity_entitlement", identityEntitlement)

		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.HTML("identity_entitlements/edit.html"))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "IdentityEntitlement was updated successfully")

	// and redirect to the identity_entitlements index page
	return c.Redirect(302, "/identity_entitlements/%s", identityEntitlement.ID)
}

// Destroy deletes a IdentityEntitlement from the DB. This function is mapped
// to the path DELETE /identity_entitlements/{identity_entitlement_id}
func (v IdentityEntitlementsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx := c.Value("tx").(*pop.Connection)

	// Allocate an empty IdentityEntitlement
	identityEntitlement := &models.IdentityEntitlement{}

	// To find the IdentityEntitlement the parameter identity_entitlement_id is used.
	if err := tx.Find(identityEntitlement, c.Param("identity_entitlement_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(identityEntitlement); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "IdentityEntitlement was destroyed successfully")

	// Redirect to the identity_entitlements index page
	return c.Redirect(302, "/identity_entitlements")
}
